#!/usr/bin/env bash
# build-glossary.sh — docs/terminology.tt.md → data/glossary.tsv («ayda аңлат» өчен).
# Глоссарий — бердәнбер чыганак; бу скрипт аны машина укый торган рәвешкә китерә.
# The glossary doc is the single source; this regenerates the data `ayda аңлат` reads.
# Баганалар / columns: term, english, meaning, type, section (TAB белән аерылган).
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")/.." && pwd)"
SRC="$HERE/docs/terminology.tt.md"
OUT="$HERE/data/glossary.tsv"

{
  echo "# GENERATED by scripts/build-glossary.sh from docs/terminology.tt.md — DO NOT EDIT."
  echo "# Төзәтмәләр docs/terminology.tt.md аша / edit the glossary doc, then rebuild."
  echo "# term	english	meaning	type	section"
  awk -F'|' '
    function trim(s) { gsub(/^[ \t]+|[ \t]+$/, "", s); return s }
    /^## / { sec = substr($0, 4); next }
    # Глоссарий юлы: беренче багана **калын** / a glossary row: bold first cell.
    /^\| \*\*/ {
      term = trim($2); gsub(/\*\*/, "", term)
      meaning = trim($3); en = trim($4)
      type = (NF >= 6) ? trim($5) : ""
      gsub(/\t/, " ", meaning)
      printf "%s\t%s\t%s\t%s\t%s\n", term, en, meaning, type, sec
    }
  ' "$SRC"
} > "$OUT"

echo "◆ Глоссарий җыелды / glossary built: data/glossary.tsv ($(grep -vc '^#' "$OUT") төшенчә)"
